### ISSUE TITLE
add SC members

### ISSUE THREAD

**Issue by cschaffner** [QCrypt/public-website#1]

**Comment by cschaffner** [comment]
It looks like the list of current SC members is the following:
Marcos Curty (University of Vigo) (chair)
Serge Fehr (CWI, Leiden University, QuSoft)
Christoph Marquardt (Max Planck Institute for the Science of Light)
Akihisa Tomita (Hokkaido University)
Hugo Zbinden (U Geneva, Switzerland) (co-chair)
Qiang Zhang (University of Science and Technology of China)
Gorjan Alagic (Univ of Maryland)
Stacey Jeffery (CWI)

**Comment by czajkowskijan** [comment]
I just couldn't find Qiang Zhang's hompage...
